name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs daily at midnight
  workflow_dispatch: # Allows manual run
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Detailed Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Vlad1343
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          
          # Isometric Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: B 
          
          # Languages (Hiding HTML/CSS)
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, jupyter notebook
          plugin_languages_details: bytes-size, percentage
          
          # Lines of code
          plugin_lines: yes

          # Style (Emerald Green)
          config_order: base.header, isocalendar, languages, achievements
          style: |
            .header { color: #059669; }
            .stat { color: #059669; }
            .field svg { fill: #059669; }