name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs daily at midnight
  workflow_dispatch: # Allows manual run
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Detailed Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Vlad1343
          template: classic
          filename: github-metrics.svg
          
          # BASE: Metadata removed to keep the bottom clean
          base: header, activity, community, repositories
          config_timezone: Europe/London
          
          # CALENDAR: Stretched half-year view
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # LINES: Show your total coding volume
          plugin_lines: yes

          # STYLE: Emerald Green & The "Zoom Out" Fix
          config_order: base.header, isocalendar, base.activity, base.community
          style: |
            /* Internal Scaling to make it harmonic with README text */
            .container { 
              transform: scale(0.85); 
              transform-origin: top center; 
              margin-bottom: -105px; 
            }
            /* Emerald Branding */
            .header { color: #059669; }
            .stat { color: #059669; }
            .field svg { fill: #059669; }